source 'https://github.com/brightcove/BrightcoveSpecs.git'

platform :ios, '10.0'
use_frameworks!

target 'example' do
  pod 'Brightcove-Player-Core'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

end
